apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-event-producer
spec:
  template:
    spec:
      containers:
        - image: salaboy/knative-event-producer:v2
          env:
            - name: K_SINK
              value: http://broker-ingress.knative-eventing.svc.cluster.local/default/default
